### ISSUE TITLE
"Authentication type is not supported" exception when "remember me" is used to log in

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-cuba#103]
In a migrated application (with `jmix-cuba` module):
- Log in with "remember me" checkbox turned on
- Exit the web browser
- Start the web browser again and enter the application (it should skip the login screen)
- Open Administration -> Application Properties
An exception occurs:
```
java.lang.RuntimeException: Authentication type is not supported: org.springframework.security.authentication.RememberMeAuthenticationToken
	at com.haulmont.cuba.core.global.impl.UserSessionSourceImpl.updateUserSessionFromAuthentication(UserSessionSourceImpl.java:99)
	at com.haulmont.cuba.core.global.impl.UserSessionSourceImpl.getUserSession(UserSessionSourceImpl.java:64)
	at com.haulmont.cuba.gui.data.impl.AbstractCollectionDatasource.<init>(AbstractCollectionDatasource.java:79)
	at com.haulmont.cuba.gui.data.impl.CollectionDatasourceImpl.<init>(CollectionDatasourceImpl.java:82)
	at com.haulmont.cuba.gui.data.impl.HierarchicalDatasourceImpl.<init>(HierarchicalDatasourceImpl.java:25)
	at com.haulmont.cuba.gui.data.impl.CustomHierarchicalDatasource.<init>(CustomHierarchicalDatasource.java:34)
	at com.haulmont.cuba.gui.app.core.appproperties.AppPropertiesDatasource.<init>(AppPropertiesDatasource.java:32)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at com.haulmont.cuba.gui.data.DsBuilder.buildHierarchicalDatasource(DsBuilder.java:453)
	at com.haulmont.cuba.gui.xml.data.DsContextLoader.loadHierarchicalDatasource(DsContextLoader.java:163)
	at com.haulmont.cuba.gui.xml.data.DsContextLoader.loadDatasources(DsContextLoader.java:98)
	at com.haulmont.cuba.web.sys.CubaScreens.loadDsContext(CubaScreens.java:592)
	at com.haulmont.cuba.web.sys.CubaScreens.initDsContext(CubaScreens.java:570)
	at com.haulmont.cuba.web.sys.CubaScreens.loadWindowFromXml(CubaScreens.java:547)
	at io.jmix.ui.sys.ScreensImpl.createScreen(ScreensImpl.java:204)
	at io.jmix.ui.sys.ScreensImpl.create(ScreensImpl.java:145)
	at com.haulmont.cuba.web.sys.CubaMenuItemCommands$CubaScreenCommand.createScreen(CubaMenuItemCommands.java:133)
	at io.jmix.ui.menu.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:242)
	at io.jmix.ui.menu.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:272)
	at io.jmix.ui.menu.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:257)
	at io.jmix.ui.component.mainwindow.impl.SideMenuImpl$MenuItemImpl.menuSelected(SideMenuImpl.java:587)
	at io.jmix.ui.widget.JmixSideMenu$1.menuItemTriggered(JmixSideMenu.java:91)
...
```

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
