### ISSUE TITLE
Filter component from compatibility schema does not work with ScreenSettingsFacet

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-cuba#110]
### Steps to reproduce
1. Download CUBA project: [ticket.zip](https://github.com/Haulmont/jmix-cuba/files/7586232/ticket.zip)

2. Launch the app to generate update scripts
3. Download migrated project to Jmix: [jmix-ticket-v3.zip](https://github.com/Haulmont/jmix-cuba/files/7586239/jmix-ticket-v3.zip)

4. Run the app.
5. Open Users screen, close it and open again
**AR**
```
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentScannerImpl$PrologDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.dom4j.io.SAXReader.read(SAXReader.java:494)
	at org.dom4j.io.SAXReader.read(SAXReader.java:408)
	at io.jmix.core.common.util.Dom4j.readDocument(Dom4j.java:60)
	at io.jmix.core.common.util.Dom4j.readDocument(Dom4j.java:54)
	at io.jmix.core.common.xmlparsing.Dom4jTools.lambda$readDocument$3(Dom4jTools.java:116)
	at io.jmix.core.common.xmlparsing.Dom4jTools.withSAXParserFromPool(Dom4jTools.java:151)
	at io.jmix.core.common.xmlparsing.Dom4jTools.readDocument(Dom4jTools.java:116)
	at com.haulmont.cuba.settings.SettingsImpl.checkLoaded(SettingsImpl.java:56)
	at com.haulmont.cuba.settings.SettingsImpl.get(SettingsImpl.java:74)
	at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl.getDefaultFilter(FilterDelegateImpl.java:1295)
	at com.haulmont.cuba.gui.components.filter.FilterDelegateImpl.loadFiltersAndApplyDefault(FilterDelegateImpl.java:603)
	at com.haulmont.cuba.web.gui.components.WebFilter.loadFiltersAndApplyDefault(WebFilter.java:112)
	at com.haulmont.cuba.gui.xml.layout.loaders.CubaFilterLoader.lambda$loadComponent$1(CubaFilterLoader.java:154)
	at io.jmix.ui.xml.layout.loader.ComponentLoaderContext.executePostInitTasks(ComponentLoaderContext.java:142)
	at io.jmix.ui.sys.ScreensImpl.createScreen(ScreensImpl.java:228)
	at io.jmix.ui.sys.ScreensImpl.create(ScreensImpl.java:145)
```

#### For Jmix screen.
Use `cubaFilter` element from compatibility schema: `xmlns:cuba="http://schemas.haulmont.com/cuba/screen/compatibility"`. Example you can find in the migrated project in _user-browse.xml_

1. Additionally make sure that the following options are saved and restored when screen uses `screenSettings` facet:
   - max result
   - expand/collapse 
   - default filter

2. Remove `screenSettings` facet from the screen. Create filter with some condition, try to edit it. 
   - "Default for me" check box shouldn't be visible.
   - Close editor. "Make deafult" action from settings button should be inactive.

#### For legacy screen
3. Try to use filter in the legacy screens (`AbstractWindow` or `AbstractLookup`).  MaxResults, expand/collapse and default filter should be saved when screen is closed and opened again. `Default for me` check box should be available in the filter editor screen.

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
