### ISSUE TITLE
Upload field for working with FileDescriptor

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-cuba#115]
- Create a CUBA project that contains:
    - Entity with FileDescriptor attribute:
        ```java
        public class Foo extends StandardEntity {

            @OneToOne(fetch = FetchType.LAZY)
            @JoinColumn(name = "ATTACHMENT_ID")
            private FileDescriptor attachment;
        ```
    - Editor screen with upload component:
        ```xml
        <upload id="attachmentField" fileStoragePutMode="IMMEDIATE" property="attachment" showFileName="true"/>
        ```

- Open the project in Jmix Studio and migrate it to Jmix
- Fix edit screen descriptor:
    ```xml
    <cuba:cubaUpload id="attachmentField" fileStoragePutMode="IMMEDIATE" property="attachment" showFileName="true"/>
    ```
- Add `cubaUpload` component to `CubaLoaderConfig.initStandardLoaders()`:
    ```java
    loaders.put("cubaUpload", CubaFileUploadFieldLoader.class);
    ```
    Publish jmix-cuba to mavenLocal.
- Start the app and open the editor screen. You'll get the exception:
    ```
    java.lang.ClassCastException: class com.haulmont.cuba.core.entity.FileDescriptor cannot be cast to class java.lang.String (com.haulmont.cuba.core.entity.FileDescriptor is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
        at io.jmix.ui.widget.JmixFileUploadField.doSetValue(JmixFileUploadField.java:32)
        at com.vaadin.ui.AbstractField.setValue(AbstractField.java:140)
        at com.vaadin.ui.AbstractField.setValue(AbstractField.java:53)
        at io.jmix.ui.component.impl.AbstractValueComponent.setValueToPresentation(AbstractValueComponent.java:125)
        at io.jmix.ui.component.impl.AbstractValueComponent.setValue(AbstractValueComponent.java:103)
        at io.jmix.ui.component.data.value.ValueBinder$ValueBindingImpl.valueSourceStateChanged(ValueBinder.java:300)
        at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
        at io.jmix.ui.component.data.value.ContainerValueSource.setState(ContainerValueSource.java:212)
        at io.jmix.ui.component.data.value.ContainerValueSource.containerItemChanged(ContainerValueSource.java:219)
        at io.jmix.core.common.event.EventHub.publish(EventHub.java:170)
        at io.jmix.ui.model.impl.InstanceContainerImpl.fireItemChanged(InstanceContainerImpl.java:167)
        at io.jmix.ui.model.impl.InstanceContainerImpl.setItem(InstanceContainerImpl.java:100)
        at io.jmix.ui.model.impl.InstanceLoaderImpl.load(InstanceLoaderImpl.java:106)
        at io.jmix.ui.model.impl.ScreenDataImpl.loadAll(ScreenDataImpl.java:90)
        at com.haulmont.cuba.gui.model.impl.AnnotationBasedLoaderBeforeShow.loadData(AnnotationBasedLoaderBeforeShow.java:36)
        at com.haulmont.cuba.web.sys.CubaScreens.fireScreenBeforeShowEvent(CubaScreens.java:654)
        at io.jmix.ui.sys.ScreensImpl.show(ScreensImpl.java:354)
    ```

### QA
1. Create CUBA project with entity that has `FileDescriptor` property;
2. Migrate it to Jmix
3. In the editor of this entity add compatibility schema:
```
xmlns:cuba="http://schemas.haulmont.com/cuba/screen/compatibility"
```
4. And use:
```
<cuba:cubaUpload id="attachmentField" fileStoragePutMode="IMMEDIATE" property="attachment" showFileName="true"/>
```
5. Launch the app and try to upload some file. No exceptions should be thrown and file should be successfully uploaded.

**Comment by reznikova21** [comment]
The "Upload" button isn't displayed
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/87806606/148930600-48bda981-9f79-4ca7-9a6e-d1272e0e0c92.png)

**Comment by Flaurite** [comment]
@reznikova21 It seems that Foo does not have a setter for attachment. Try to add a setter, and it should work.

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
