### ISSUE TITLE
JMX console screen doesn't open in jmix-cuba project

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-cuba#41]
- Create a Jmix project
- Add jmix-cuba dependency
- Click Administration -> JMX console

The screen doesn't open. An exception in the log:

```
Caused by: io.jmix.ui.GuiDevelopmentException: Table 'rows' element doesn't have 'datasource' attribute, params={Table ID=mbeansTable}, frameId=ui_JmxConsoleScreen
	at com.haulmont.cuba.gui.xml.data.DatasourceLoaderHelper.loadTableDatasource(DatasourceLoaderHelper.java:167)
	at com.haulmont.cuba.gui.xml.layout.loaders.CubaGroupTableLoader.initTableDataHolder(CubaGroupTableLoader.java:55)
	at io.jmix.ui.xml.layout.loader.AbstractTableLoader.loadTableData(AbstractTableLoader.java:144)
	at com.haulmont.cuba.gui.xml.layout.loaders.CubaGroupTableLoader.loadTableData(CubaGroupTableLoader.java:88)
	at io.jmix.ui.xml.layout.loader.AbstractTableLoader.loadComponent(AbstractTableLoader.java:135)
	at io.jmix.ui.xml.layout.loader.GroupTableLoader.loadComponent(GroupTableLoader.java:44)
	at com.haulmont.cuba.gui.xml.layout.loaders.CubaGroupTableLoader.loadComponent(CubaGroupTableLoader.java:43)
	at io.jmix.ui.xml.layout.loader.ContainerLoader.loadSubComponents(ContainerLoader.java:36)
	at io.jmix.ui.xml.layout.loader.ContainerLoader.loadSubComponentsAndExpand(ContainerLoader.java:74)
	at io.jmix.ui.xml.layout.loader.WindowLoader.loadComponent(WindowLoader.java:88)
	at io.jmix.ui.sys.ScreensImpl.loadWindowFromXml(ScreensImpl.java:323)
	at com.haulmont.cuba.web.sys.CubaScreens.loadWindowFromXml(CubaScreens.java:502)
	at io.jmix.ui.sys.ScreensImpl.createScreen(ScreensImpl.java:201)
	at io.jmix.ui.sys.ScreensImpl.create(ScreensImpl.java:142)
	at io.jmix.ui.menu.MenuItemCommands$ScreenCommand.createScreen(MenuItemCommands.java:306)
	at com.haulmont.cuba.web.sys.CubaMenuItemCommands$CubaScreenCommand.createScreen(CubaMenuItemCommands.java:136)
	at io.jmix.ui.menu.MenuItemCommands$ScreenCommand.run(MenuItemCommands.java:242)
	at io.jmix.ui.menu.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:272)
	at io.jmix.ui.menu.SideMenuBuilder$MenuCommandExecutor.accept(SideMenuBuilder.java:257)
	at io.jmix.ui.component.mainwindow.impl.SideMenuImpl$MenuItemImpl.menuSelected(SideMenuImpl.java:587)
	at io.jmix.ui.widget.JmixSideMenu$1.menuItemTriggered(JmixSideMenu.java:91)
	... 88 more
```

Also, the standard exception dialog is not shown, presumably because of the following exception:
```
Exception in handlers:
java.lang.ClassCastException: com.sun.proxy.$Proxy219 cannot be cast to com.haulmont.cuba.gui.WindowManager
	at com.haulmont.cuba.gui.exception.GenericExceptionHandler.handle(GenericExceptionHandler.java:42)
	at io.jmix.ui.exception.ExceptionHandlers.handle(ExceptionHandlers.java:114)
	at io.jmix.ui.AppUI.error(AppUI.java:436)
	at com.vaadin.server.LegacyCommunicationManager.handleConnectorRelatedException(LegacyCommunicationManager.java:426)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:434)
	at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:396)
	at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:260)
	at com.vaadin.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:82)
	at com.vaadin.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.server.VaadinService.handleRequest(VaadinService.java:1578)
	at com.vaadin.server.VaadinServlet.service(VaadinServlet.java:425)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
...
```

**Comment by Flaurite** [comment]
1. The issue with screen will be fixed in: [Haulmont/jmix-ui#376](https://github.com/Haulmont/jmix-ui/issues/376)
2. The issue with ClassCastException wil be fixed in: [Haulmont/jmix-ui#375](https://github.com/Haulmont/jmix-ui/issues/375)
