### ISSUE TITLE
"Unable to access value holder for property" for @OneToOne relation with embedded entity

### ISSUE THREAD

**Issue by dtaimanov** [Haulmont/jmix-cuba#51]
#### Problem
CUBA project has been migrated to Jmix platform. It has Entity with embedded property and self-reference. Trying to edit entity with not null self-reference leads to exception: 
```
java.lang.RuntimeException: Unable to access value holder for property: homeAddress on entity com.haulmont.samples.ratlab.entity.stuff.Employee
	at io.jmix.eclipselink.impl.lazyloading.ValueHoldersSupport.getSingleValueHolder(ValueHoldersSupport.java:38)
	at io.jmix.eclipselink.impl.lazyloading.AbstractValueHolder.replaceLoadOptions(AbstractValueHolder.java:346)
	at io.jmix.eclipselink.impl.lazyloading.AbstractSingleValueHolder$SingleValuePropertyVisitor.visit(AbstractSingleValueHolder.java:51)
	at io.jmix.core.MetadataTools.internalTraverseAttributes(MetadataTools.java:1138)
	at io.jmix.core.MetadataTools.traverseAttributes(MetadataTools.java:898)
	at io.jmix.eclipselink.impl.lazyloading.AbstractSingleValueHolder.afterLoadValue(AbstractSingleValueHolder.java:38)
	at io.jmix.eclipselink.impl.lazyloading.AbstractValueHolder.getValue(AbstractValueHolder.java:276)
	at com.haulmont.samples.ratlab.entity.stuff.Employee._persistence_get_supervisor(Employee.java)
	at com.haulmont.samples.ratlab.entity.stuff.Employee.getSupervisor(Employee.java:67)
	at io.jmix.core.entity.BaseEntityEntry.getAttributeValue(BaseEntityEntry.java:74)
	at io.jmix.core.entity.EntityValues.getValue(EntityValues.java:94)
	at io.jmix.core.entity.EntityValues.getValueEx(EntityValues.java:125)
       ...

```

#### Steps:
1. Download and run [project](https://app.zenhub.com/files/172435360/989ec87c-edc1-40be-9ae1-97cc93ed86d0/download)
2. Open Employees screen (there are two employees: one of them is supervisor for another. Both has adress fields filled):
![изображение.png](https://images.zenhubusercontent.com/5ed6636766d0991824e90fb6/a07e36c1-4d66-4dc1-9ea1-4209a070f8c2)
![изображение.png](https://images.zenhubusercontent.com/5ed6636766d0991824e90fb6/8315ba0a-1d85-4abe-ab3f-b820a278dd13)
3. Refresh table and try to edit entity with not empty "Supervisor" property.
**ER:** Editor screen openned
**AR:** Exception (see above)
![изображение.png](https://images.zenhubusercontent.com/5ed6636766d0991824e90fb6/d4b52e56-c6cc-4107-8788-8a38a4d104fa)

**Comment by klaus7** [comment]
I've got the same problem from what I see. I can't the download the project from above though.

**Comment by knstvk** [comment]
The problem is also reproduced in `LazyLoadingTest` if you add a transient field to this test entity:

```
package test_support.entity.lazyloading;

import io.jmix.core.metamodel.annotation.DependsOnProperties;
import io.jmix.core.metamodel.annotation.JmixEntity;
import io.jmix.core.metamodel.annotation.JmixProperty;
import test_support.entity.BaseEntity;

import javax.persistence.*;

@Table(name = "TEST_MANY_TO_ONE_ENTITY")
@JmixEntity
@Entity(name = "test_ManyToOneEntity")
public class ManyToOneEntity extends BaseEntity {
    @Column(name = "NAME")
    protected String name;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TEST_ONE_TO_MANY_ENTITY_ID")
    protected OneToManyEntity oneToManyEntity;

    @Transient
    @JmixProperty
    @DependsOnProperties({"oneToManyEntity"})
    private OneToManyEntity transientField;
    
    // getters and setters
}
```
