### ISSUE TITLE
Using the CUBA module breaks integration test for empty addon

### ISSUE THREAD

**Issue by mariodavid** [Haulmont/jmix-cuba#80]
Hi,

When creating an empty addon and add the CUBA module into it in order to use some legacy APIs, it causes the integration tests to fail:

```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'io.jmix.securityui.constraint.UiPolicyStore' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1790)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1346)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657)
	... 198 more
```

See also attached example:
[empty-addon.zip](https://github.com/Haulmont/jmix-cuba/files/7151808/empty-addon.zip)

**Comment by knstvk** [comment]
You also need to include jmix-security and jmix-security-ui starters to the add-on's `build.gradle`:
```
    implementation 'io.jmix.cuba:jmix-cuba-starter'
    implementation 'io.jmix.security:jmix-security-starter'
    implementation 'io.jmix.security:jmix-security-ui-starter'
```
