### ISSUE TITLE
Error migrating CUBA project:`sec_user_substitution` table already exists

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-cuba#87]
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3568-212
IntelliJ version: IntelliJ IDEA 2021.2.2 (Ultimate Edition)

cuba [Uploading dynamic.zip…]()
 TC: migrate attached cuba project to Jmix
run app
AR:
```
Unexpected error running Liquibase: Migration failed for change set io/jmix/securitydata/liquibase/changelog/003-security-data.xml::1::security-data:
     Reason: liquibase.exception.DatabaseException: ОШИБКА: отношение "sec_user_substitution" уже существует [Failed SQL: (0) CREATE TABLE public.SEC_USER_SUBSTITUTION (ID UUID NOT NULL, VERSION INTEGER DEFAULT 1 NOT NULL, CREATE_TS TIMESTAMP WITHOUT TIME ZONE, CREATED_BY VARCHAR(50), UPDATE_TS TIMESTAMP WITHOUT TIME ZONE, UPDATED_BY VARCHAR(50), DELETE_TS TIMESTAMP WITHOUT TIME ZONE, DELETED_BY VARCHAR(50), USERNAME VARCHAR(255) NOT NULL, SUBSTITUTED_USERNAME VARCHAR(255) NOT NULL, START_DATE TIMESTAMP WITHOUT TIME ZONE, END_DATE TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT SEC_USER_SUBSTITUTION_PKEY PRIMARY KEY (ID))]
For more information, please use the --logLevel flag
[2021-09-29 15:57:21] SEVERE [liquibase.integration] Unexpected error running Liquibase: Migration failed for change set io/jmix/securitydata/liquibase/changelog/003-security-data.xml::1::security-data:
     Reason: liquibase.exception.DatabaseException: ОШИБКА: отношение "sec_user_substitution" уже существует [Failed SQL: (0) CREATE TABLE public.SEC_USER_SUBSTITUTION (ID UUID NOT NULL, VERSION INTEGER DEFAULT 1 NOT NULL, CREATE_TS TIMESTAMP WITHOUT TIME ZONE, CREATED_BY VARCHAR(50), UPDATE_TS TIMESTAMP WITHOUT TIME ZONE, UPDATED_BY VARCHAR(50), DELETE_TS TIMESTAMP WITHOUT TIME ZONE, DELETED_BY VARCHAR(50), USERNAME VARCHAR(255) NOT NULL, SUBSTITUTED_USERNAME VARCHAR(255) NOT NULL, START_DATE TIMESTAMP WITHOUT TIME ZONE, END_DATE TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT SEC_USER_SUBSTITUTION_PKEY PRIMARY KEY (ID))]
liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set io/jmix/securitydata/liquibase/changelog/003-security-data.xml::1::security-data:
     Reason: liquibase.exception.DatabaseException: ОШИБКА: отношение "sec_user_substitution" уже существует [Failed SQL: (0) CREATE TABLE public.SEC_USER_SUBSTITUTION (ID UUID NOT NULL, VERSION INTEGER DEFAULT 1 NOT NULL, CREATE_TS TIMESTAMP WITHOUT TIME ZONE, CREATED_BY VARCHAR(50), UPDATE_TS TIMESTAMP WITHOUT TIME ZONE, UPDATED_BY VARCHAR(50), DELETE_TS TIMESTAMP WITHOUT TIME ZONE, DELETED_BY VARCHAR(50), USERNAME VARCHAR(255) NOT NULL, SUBSTITUTED_USERNAME VARCHAR(255) NOT NULL, START_DATE TIMESTAMP WITHOUT TIME ZONE, END_DATE TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT SEC_USER_SUBSTITUTION_PKEY PRIMARY KEY (ID))]
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:124)
	at liquibase.Liquibase.lambda$null$0(Liquibase.java:272)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.Scope.child(Scope.java:222)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:271)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.Liquibase.runInScope(Liquibase.java:2369)
	at liquibase.Liquibase.update(Liquibase.java:217)
	at liquibase.Liquibase.update(Liquibase.java:203)
	at liquibase.integration.commandline.Main.doMigration(Main.java:1802)
	at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:367)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.integration.commandline.Main$1.run(Main.java:366)
	at liquibase.integration.commandline.Main$1.run(Main.java:196)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:145)
	at liquibase.integration.commandline.Main.run(Main.java:196)
	at liquibase.integration.commandline.Main.main(Main.java:158)
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set io/jmix/securitydata/liquibase/changelog/003-security-data.xml::1::security-data:
     Reason: liquibase.exception.DatabaseException: ОШИБКА: отношение "sec_user_substitution" уже существует [Failed SQL: (0) CREATE TABLE public.SEC_USER_SUBSTITUTION (ID UUID NOT NULL, VERSION INTEGER DEFAULT 1 NOT NULL, CREATE_TS TIMESTAMP WITHOUT TIME ZONE, CREATED_BY VARCHAR(50), UPDATE_TS TIMESTAMP WITHOUT TIME ZONE, UPDATED_BY VARCHAR(50), DELETE_TS TIMESTAMP WITHOUT TIME ZONE, DELETED_BY VARCHAR(50), USERNAME VARCHAR(255) NOT NULL, SUBSTITUTED_USERNAME VARCHAR(255) NOT NULL, START_DATE TIMESTAMP WITHOUT TIME ZONE, END_DATE TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT SEC_USER_SUBSTITUTION_PKEY PRIMARY KEY (ID))]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:672)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:49)
	at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:111)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:110)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.Scope.child(Scope.java:222)
	at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:94)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.Scope.child(Scope.java:222)
	at liquibase.Scope.child(Scope.java:226)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:66)
	... 26 more
Caused by: liquibase.exception.DatabaseException: ОШИБКА: отношение "sec_user_substitution" уже существует [Failed SQL: (0) CREATE TABLE public.SEC_USER_SUBSTITUTION (ID UUID NOT NULL, VERSION INTEGER DEFAULT 1 NOT NULL, CREATE_TS TIMESTAMP WITHOUT TIME ZONE, CREATED_BY VARCHAR(50), UPDATE_TS TIMESTAMP WITHOUT TIME ZONE, UPDATED_BY VARCHAR(50), DELETE_TS TIMESTAMP WITHOUT TIME ZONE, DELETED_BY VARCHAR(50), USERNAME VARCHAR(255) NOT NULL, SUBSTITUTED_USERNAME VARCHAR(255) NOT NULL, START_DATE TIMESTAMP WITHOUT TIME ZONE, END_DATE TIMESTAMP WITHOUT TIME ZONE, CONSTRAINT SEC_USER_SUBSTITUTION_PKEY PRIMARY KEY (ID))]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:393)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:82)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:150)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1278)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1260)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
	... 46 more
Caused by: org.postgresql.util.PSQLException: ОШИБКА: отношение "sec_user_substitution" уже существует
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2552)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2284)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:389)
	... 51 more

```

**Comment by maistrenkoIulia** [comment]
verified
